"use client";

import { useEffect, useId, useRef, useState } from "react";
import PhoneInput from "react-phone-number-input";
import "react-phone-number-input/style.css";
import { DndContext, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, sortableKeyboardCoordinates, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { ChevronDown, Eye, EyeOff, GripVertical, ImagePlus, Plus, Trash2, X } from "lucide-react";
import { copy, sectionLabel } from "@/lib/i18n";
import type { CVDocument, Locale, SectionId, TemplateId } from "@/types/cv";
import { PhotoCropper } from "./photo-cropper";

type Props = { document: CVDocument; locale: Locale; mode: "content" | "design"; onChange: (document: CVDocument) => void; onCloseSettings: () => void };
export const templates: { id: TemplateId; name: string }[] = [
  { id: "ats", name: "ATS" }, { id: "professional", name: "Profesional" }, { id: "modern", name: "Modern" },
  { id: "minimal", name: "Minimal" }, { id: "creative", name: "Kreatif" }, { id: "academic", name: "Akademik" },
];

function Field({ label, value, onChange, type = "text", placeholder, textarea, wide }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string; textarea?: boolean; wide?: boolean }) {
  const id = useId();
  return <label className={`field ${(textarea || wide) ? "field-wide" : ""}`} htmlFor={id}><span>{label}</span>{textarea ? <textarea id={id} value={value} placeholder={placeholder} rows={3} onChange={(event) => onChange(event.target.value)} /> : <input id={id} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} autoComplete={type === "email" ? "email" : "off"} />}</label>;
}

function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) {
  const [draft, setDraft] = useState(value);
  const timer = useRef(0);
  const latest = useRef(value);
  useEffect(() => () => window.clearTimeout(timer.current), []);
  const update = (next: string) => {
    latest.current = next;
    setDraft(next);
    window.clearTimeout(timer.current);
    timer.current = window.setTimeout(() => onChange(latest.current), 90);
  };
  return <label className="field color-field"><span>{label}</span><div className="color-input"><input type="color" defaultValue={value} onInput={(event) => update(event.currentTarget.value)} onChange={(event) => update(event.currentTarget.value)} /><code>{draft}</code></div></label>;
}

function ItemShell({ summary, children, onDelete, onUp, onDown }: { summary: string; children: React.ReactNode; onDelete: () => void; onUp?: () => void; onDown?: () => void }) {
  return <details className="repeat-item" open><summary><span>{summary || "Item baru"}</span><ChevronDown size={15} /></summary><div className="item-actions"><button onClick={onUp} disabled={!onUp} aria-label="Move up">↑</button><button onClick={onDown} disabled={!onDown} aria-label="Move down">↓</button><button onClick={onDelete} aria-label="Delete item"><Trash2 size={14} /></button></div><div className="repeat-content">{children}</div></details>;
}

function SortableSection({ id, title, hidden, locale, onTitle, onToggle, children }: { id: SectionId; title: string; hidden: boolean; locale: Locale; onTitle: (value: string) => void; onToggle: () => void; children: React.ReactNode }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id });
  return <section ref={setNodeRef} className={`form-section sortable-section ${isDragging ? "dragging" : ""}`} style={{ transform: CSS.Transform.toString(transform), transition }}>
    <div className="section-title-row"><button className="drag-handle" {...attributes} {...listeners} aria-label={`Move ${sectionLabel(id, locale)}`}><GripVertical size={16} /></button><input aria-label={`${sectionLabel(id, locale)} title`} value={title} onChange={(event) => onTitle(event.target.value)} /><button className="visibility-button icon-only" onClick={onToggle} aria-label={hidden ? "Show section" : "Hide section"}>{hidden ? <EyeOff size={15} /> : <Eye size={15} />}</button></div>
    <div className={hidden ? "section-content dimmed" : "section-content"}>{children}</div>
  </section>;
}

export function EditorPanel({ document: cv, locale, mode, onChange, onCloseSettings }: Props) {
  const t = copy[locale];
  const [cropSource, setCropSource] = useState<string | null>(null);
  const photoInput = useRef<HTMLInputElement>(null);
  const sensors = useSensors(useSensor(PointerSensor), useSensor(KeyboardSensor, { coordinateGetter: sortableKeyboardCoordinates }));
  const patch = (changes: Partial<CVDocument>) => onChange({ ...cv, ...changes, updatedAt: new Date().toISOString() });
  const patchPersonal = (key: keyof typeof cv.content.personal, value: string) => patch({ content: { ...cv.content, personal: { ...cv.content.personal, [key]: value } } });
  const patchContent = <K extends keyof typeof cv.content>(key: K, value: (typeof cv.content)[K]) => patch({ content: { ...cv.content, [key]: value } });
  const moveItem = <T,>(items: T[], index: number, direction: -1 | 1) => { const next = [...items]; const target = index + direction; [next[index], next[target]] = [next[target], next[index]]; return next; };
  type ListKey = Exclude<keyof typeof cv.content, "personal" | "summary">;
  const updateItem = (key: ListKey, index: number, changes: Record<string, unknown>) => { const items = [...cv.content[key]] as unknown as Array<Record<string, unknown>>; items[index] = { ...items[index], ...changes }; patchContent(key, items as never); };
  const itemOps = <T,>(key: ListKey, items: T[], index: number) => ({ onDelete: () => patchContent(key, items.filter((_, itemIndex) => itemIndex !== index) as never), onUp: index > 0 ? () => patchContent(key, moveItem(items, index, -1) as never) : undefined, onDown: index < items.length - 1 ? () => patchContent(key, moveItem(items, index, 1) as never) : undefined });
  const add = (key: ListKey) => {
    const id = crypto.randomUUID();
    const values = {
      experience: { id, position: "", company: "", location: "", startDate: "", endDate: "", current: false, description: "" },
      education: { id, degree: "", school: "", location: "", startDate: "", endDate: "", description: "" },
      skills: { id, name: "", items: [] }, awards: { id, title: "", issuer: "", date: "", description: "", url: "" },
      certifications: { id, name: "", issuer: "", date: "", expiryDate: "", credentialId: "", url: "" },
      languages: { id, name: "", level: "" }, projects: { id, name: "", url: "", description: "" },
      volunteer: { id, organization: "", role: "", startDate: "", endDate: "", current: false, description: "" },
    };
    patchContent(key, [...cv.content[key], values[key] as never] as never);
  };
  const dragEnd = ({ active, over }: DragEndEvent) => { if (!over || active.id === over.id) return; patch({ sectionOrder: arrayMove(cv.sectionOrder, cv.sectionOrder.indexOf(active.id as SectionId), cv.sectionOrder.indexOf(over.id as SectionId)) }); };
  const sectionProps = (id: SectionId) => ({ id, locale, title: cv.sectionTitles[id], hidden: cv.hiddenSections.includes(id), onTitle: (value: string) => patch({ sectionTitles: { ...cv.sectionTitles, [id]: value } }), onToggle: () => patch({ hiddenSections: cv.hiddenSections.includes(id) ? cv.hiddenSections.filter((item) => item !== id) : [...cv.hiddenSections, id] }) });
  const addButton = (key: ListKey, label: string) => <button className="add-button" onClick={() => add(key)}><Plus size={14} /> {locale === "id" ? "Tambah" : "Add"} {label}</button>;

  if (mode === "design") return <div className="editor-scroll settings-view"><div className="settings-head"><div><span className="eyebrow">CVKita</span><h2>{t.design}</h2></div><button className="toolbar-button icon-only" onClick={onCloseSettings} aria-label={t.close}><X size={17} /></button></div>
    <section className="settings-section"><h3>{t.template}</h3><div className="template-grid">{templates.map((template) => <button key={template.id} className={`template-option ${cv.templateId === template.id ? "selected" : ""}`} onClick={() => patch({ templateId: template.id })}><span className={`template-thumb thumb-${template.id}`}><i /><i /><i /></span><strong>{template.name}</strong></button>)}</div></section>
    <section className="settings-section"><h3>{t.design}</h3><div className="field-grid"><ColorField key={`accent-${cv.id}`} label={t.accent} value={cv.design.accentColor} onChange={(accentColor) => patch({ design: { ...cv.design, accentColor } })} /><ColorField key={`text-${cv.id}`} label={locale === "id" ? "Warna teks" : "Text color"} value={cv.design.textColor} onChange={(textColor) => patch({ design: { ...cv.design, textColor } })} /><ColorField key={`border-${cv.id}`} label={locale === "id" ? "Warna border" : "Border color"} value={cv.design.borderColor} onChange={(borderColor) => patch({ design: { ...cv.design, borderColor } })} /><label className="field"><span>{t.font}</span><select value={cv.design.fontFamily} onChange={(event) => patch({ design: { ...cv.design, fontFamily: event.target.value as typeof cv.design.fontFamily } })}><option value="Helvetica">Arial / Helvetica</option><option value="Times-Roman">Times New Roman / Serif</option><option value="Courier">Courier</option></select></label><label className="field"><span>{locale === "id" ? "Ukuran judul" : "Title size"}</span><select value={cv.design.titleSize} onChange={(event) => patch({ design: { ...cv.design, titleSize: Number(event.target.value) as 14 | 15 | 16 } })}><option value={14}>14 pt</option><option value={15}>15 pt</option><option value={16}>16 pt</option></select></label><label className="field"><span>{locale === "id" ? "Ukuran teks utama" : "Body text size"}</span><select value={cv.design.bodySize} onChange={(event) => patch({ design: { ...cv.design, bodySize: 12 } })}><option value={12}>12 pt</option></select></label><label className="field field-wide"><span>{t.textSize}: {cv.design.fontScale}%</span><input type="range" min={90} max={110} value={cv.design.fontScale} onChange={(event) => patch({ design: { ...cv.design, fontScale: Number(event.target.value) } })} /></label><label className="field"><span>{t.margin}</span><select value={cv.design.marginPreset} onChange={(event) => patch({ design: { ...cv.design, marginPreset: Number(event.target.value) as 12 | 16 | 20 } })}><option value={12}>12 mm</option><option value={16}>16 mm</option><option value={20}>20 mm</option></select></label><label className="field"><span>{t.density}</span><select value={cv.design.density} onChange={(event) => patch({ design: { ...cv.design, density: event.target.value as typeof cv.design.density } })}><option value="compact">{t.compact}</option><option value="normal">{t.normal}</option><option value="loose">{t.loose}</option></select></label></div></section>
  </div>;

  const renderSection = (id: SectionId) => {
    const p = sectionProps(id);
    if (id === "summary") return <SortableSection key={id} {...p}><label className="field"><textarea aria-label={t.summary} maxLength={500} rows={4} value={cv.content.summary} placeholder={locale === "id" ? "Tulis ringkasan profesional singkat…" : "Write a brief professional summary…"} onChange={(event) => patchContent("summary", event.target.value)} /></label><p className="character-count">{cv.content.summary.length}/500</p></SortableSection>;
    if (id === "experience") return <SortableSection key={id} {...p}>{cv.content.experience.map((item, index) => <ItemShell key={item.id} summary={[item.position, item.company].filter(Boolean).join(" · ")} {...itemOps(id, cv.content.experience, index)}><div className="field-grid"><Field label={t.position} value={item.position} onChange={(value) => updateItem(id, index, { position: value })} /><Field label={t.company} value={item.company} onChange={(value) => updateItem(id, index, { company: value })} /><Field label={t.location} value={item.location} onChange={(value) => updateItem(id, index, { location: value })} /><Field label={t.start} value={item.startDate} onChange={(value) => updateItem(id, index, { startDate: value })} /><Field label={t.end} value={item.endDate} onChange={(value) => updateItem(id, index, { endDate: value })} /><label className="check-field"><input type="checkbox" checked={item.current} onChange={(event) => updateItem(id, index, { current: event.target.checked })} />{t.current}</label><Field label={t.description} value={item.description} onChange={(value) => updateItem(id, index, { description: value })} textarea /></div></ItemShell>)}{addButton(id, t.experience)}</SortableSection>;
    if (id === "education") return <SortableSection key={id} {...p}>{cv.content.education.map((item, index) => <ItemShell key={item.id} summary={[item.degree, item.school].filter(Boolean).join(" · ")} {...itemOps(id, cv.content.education, index)}><div className="field-grid"><Field label={t.degree} value={item.degree} onChange={(value) => updateItem(id, index, { degree: value })} /><Field label={t.school} value={item.school} onChange={(value) => updateItem(id, index, { school: value })} /><Field label={t.location} value={item.location} onChange={(value) => updateItem(id, index, { location: value })} /><Field label={t.start} value={item.startDate} onChange={(value) => updateItem(id, index, { startDate: value })} /><Field label={t.end} value={item.endDate} onChange={(value) => updateItem(id, index, { endDate: value })} /><Field label={t.description} value={item.description} onChange={(value) => updateItem(id, index, { description: value })} textarea /></div></ItemShell>)}{addButton(id, t.education)}</SortableSection>;
    if (id === "skills") return <SortableSection key={id} {...p}>{cv.content.skills.map((item, index) => <ItemShell key={item.id} summary={item.name} {...itemOps(id, cv.content.skills, index)}><div className="field-grid"><Field label={locale === "id" ? "Nama kategori" : "Category name"} value={item.name} onChange={(value) => updateItem(id, index, { name: value })} /><Field label={locale === "id" ? "Keahlian (pisahkan dengan koma)" : "Skills (comma separated)"} value={item.items.join(", ")} onChange={(value) => updateItem(id, index, { items: value.split(",").map((entry) => entry.trim()).filter(Boolean) })} wide /></div></ItemShell>)}{addButton(id, locale === "id" ? "kategori" : "category")}</SortableSection>;
    if (id === "awards") return <SortableSection key={id} {...p}>{cv.content.awards.map((item, index) => <ItemShell key={item.id} summary={item.title} {...itemOps(id, cv.content.awards, index)}><div className="field-grid"><Field label={locale === "id" ? "Nama penghargaan" : "Award title"} value={item.title} onChange={(value) => updateItem(id, index, { title: value })} /><Field label={t.issuer} value={item.issuer} onChange={(value) => updateItem(id, index, { issuer: value })} /><Field label={locale === "id" ? "Tanggal" : "Date"} value={item.date} onChange={(value) => updateItem(id, index, { date: value })} /><Field label={t.link} value={item.url} onChange={(value) => updateItem(id, index, { url: value })} /><Field label={t.description} value={item.description} onChange={(value) => updateItem(id, index, { description: value })} textarea /></div></ItemShell>)}{addButton(id, t.awards)}</SortableSection>;
    if (id === "certifications") return <SortableSection key={id} {...p}>{cv.content.certifications.map((item, index) => <ItemShell key={item.id} summary={item.name} {...itemOps(id, cv.content.certifications, index)}><div className="field-grid"><Field label={t.name} value={item.name} onChange={(value) => updateItem(id, index, { name: value })} /><Field label={t.issuer} value={item.issuer} onChange={(value) => updateItem(id, index, { issuer: value })} /><Field label={locale === "id" ? "Tanggal terbit" : "Issue date"} value={item.date} onChange={(value) => updateItem(id, index, { date: value })} /><Field label={locale === "id" ? "Kedaluwarsa" : "Expiry date"} value={item.expiryDate} onChange={(value) => updateItem(id, index, { expiryDate: value })} /><Field label="Credential ID" value={item.credentialId} onChange={(value) => updateItem(id, index, { credentialId: value })} /><Field label={t.link} value={item.url} onChange={(value) => updateItem(id, index, { url: value })} /></div></ItemShell>)}{addButton(id, t.certifications)}</SortableSection>;
    if (id === "languages") return <SortableSection key={id} {...p}>{cv.content.languages.map((item, index) => <ItemShell key={item.id} summary={item.name} {...itemOps(id, cv.content.languages, index)}><div className="field-grid"><Field label={t.name} value={item.name} onChange={(value) => updateItem(id, index, { name: value })} /><Field label={t.level} value={item.level} onChange={(value) => updateItem(id, index, { level: value })} /></div></ItemShell>)}{addButton(id, t.languages)}</SortableSection>;
    if (id === "projects") return <SortableSection key={id} {...p}>{cv.content.projects.map((item, index) => <ItemShell key={item.id} summary={item.name} {...itemOps(id, cv.content.projects, index)}><div className="field-grid"><Field label={t.name} value={item.name} onChange={(value) => updateItem(id, index, { name: value })} /><Field label={t.link} value={item.url} onChange={(value) => updateItem(id, index, { url: value })} /><Field label={t.description} value={item.description} onChange={(value) => updateItem(id, index, { description: value })} textarea /></div></ItemShell>)}{addButton(id, t.projects)}</SortableSection>;
    return <SortableSection key={id} {...p}>{cv.content.volunteer.map((item, index) => <ItemShell key={item.id} summary={[item.role, item.organization].filter(Boolean).join(" · ")} {...itemOps(id, cv.content.volunteer, index)}><div className="field-grid"><Field label={locale === "id" ? "Peran" : "Role"} value={item.role} onChange={(value) => updateItem(id, index, { role: value })} /><Field label={locale === "id" ? "Organisasi" : "Organization"} value={item.organization} onChange={(value) => updateItem(id, index, { organization: value })} /><Field label={t.start} value={item.startDate} onChange={(value) => updateItem(id, index, { startDate: value })} /><Field label={t.end} value={item.endDate} onChange={(value) => updateItem(id, index, { endDate: value })} /><label className="check-field"><input type="checkbox" checked={item.current} onChange={(event) => updateItem(id, index, { current: event.target.checked })} />{locale === "id" ? "Masih aktif di sini" : "Currently active here"}</label><Field label={t.description} value={item.description} onChange={(value) => updateItem(id, index, { description: value })} textarea /></div></ItemShell>)}{addButton(id, t.volunteer)}</SortableSection>;
  };

  return <div className="editor-scroll">
    <section className="form-section personal-section"><h2>{t.personal}</h2><div className="field-grid"><Field label={t.fullName} value={cv.content.personal.fullName} onChange={(value) => patchPersonal("fullName", value)} placeholder="Nadia Pratama" /><Field label={t.role} value={cv.content.personal.role} onChange={(value) => patchPersonal("role", value)} placeholder="Product Designer" /><Field label={t.email} value={cv.content.personal.email} onChange={(value) => patchPersonal("email", value)} type="email" /><label className="field"><span>{t.phone}</span><PhoneInput international defaultCountry="ID" value={cv.content.personal.phone} onChange={(value) => patchPersonal("phone", value || "")} /></label><Field label={t.location} value={cv.content.personal.location} onChange={(value) => patchPersonal("location", value)} /><Field label={t.website} value={cv.content.personal.website} onChange={(value) => patchPersonal("website", value)} /><Field label={t.linkedin} value={cv.content.personal.linkedin} onChange={(value) => patchPersonal("linkedin", value)} wide /></div><label className="photo-toggle"><input type="checkbox" checked={cv.design.showPhoto} onChange={(event) => patch({ design: { ...cv.design, showPhoto: event.target.checked } })} /><span>{t.photo}</span></label>{cv.design.showPhoto ? <div className="photo-row"><div className="photo-preview">{cv.content.personal.photo ? <img src={cv.content.personal.photo} alt="" /> : <span>{(cv.content.personal.fullName || "CV").slice(0, 2).toUpperCase()}</span>}</div><div><button className="add-button" onClick={() => photoInput.current?.click()}><ImagePlus size={14} />{t.uploadPhoto}</button>{cv.content.personal.photo ? <button className="text-button danger" onClick={() => patchPersonal("photo", "")}>{t.removePhoto}</button> : null}</div><input ref={photoInput} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 8_000_000) return alert("Maximum file size is 8 MB."); const reader = new FileReader(); reader.onload = () => setCropSource(String(reader.result)); reader.readAsDataURL(file); event.currentTarget.value = ""; }} /></div> : null}</section>
    <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}><SortableContext items={cv.sectionOrder} strategy={verticalListSortingStrategy}>{cv.sectionOrder.map(renderSection)}</SortableContext></DndContext>
    {cropSource ? <PhotoCropper source={cropSource} onCancel={() => setCropSource(null)} onSave={(image) => { patchPersonal("photo", image); setCropSource(null); }} /> : null}
  </div>;
}
